services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"

  python:
    build:
      context: .
    command: ["--user", "root",
              "--password", "root",
              "--host", "pgdatabase",
              "--port", "5432",
              "--database", "ny_taxi",
              "--trips_table_name", "yellow_taxi_trips",
              "--zones_table_name", "taxi_zones",
              "--url_trips", "https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-10.csv.gz",
              "--url_zones", "https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv"]
    depends_on:
      pgdatabase:
        condition: service_started
    